- name: "Sparta 2.0"
  hosts: localhost
  connection: local
  tasks:
    - name: Create ./downloads directory
      file:
        path: ./downloads
        state: directory

    - name: Download openshift-install-linux.tar.gz
      get_url:
        dest: ./downloads/openshift-install-linux.tar.gz
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux.tar.gz"

    - name: Download openshift-client-linux.tar.gz
      get_url:
        dest: ./downloads/openshift-client-linux.tar.gz
        url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/openshift-client-linux.tar.gz"

    - name: Download oc-mirror.tar.gz
      get_url:
        dest: ./downloads/oc-mirror.tar.gz
        url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/oc-mirror.tar.gz"

    - name: Download rhcos-live.x86_64.iso
      get_url:
        dest: ./downloads/rhcos-live.x86_64.iso
        url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/latest/rhcos-live.x86_64.iso"

    - name: Stat docker-registry image tarball
      stat:
        path: ./downloads/docker-registry-image-latest.tar.gz
      register: docker_registry_image

    - name: Download docker-registry image tarball
      command:
        cmd: "skopeo copy docker://docker.io/registry:latest docker-archive:./downloads/docker-registry-image-latest.tar.gz"
      when: "not docker_registry_image.stat.exists"
